name: healthcare-db

services:
  # Postgres
  pg:
    image: postgres:15.3-alpine
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./volumes/databases/pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:7-alpine
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./volumes/databases/redis:/data

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'  # Web UI
      - '${SMTP_PORT}:1025'  # SMTP
    environment:
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

  # PgAdmin
  pg-admin:
    image: dpage/pgadmin4:6
    ports:
      - '${PGADMIN_PORT}:5050'
    volumes:
      - ./volumes/databases/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - pg