name: nestjs-auth-api

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_URL}:8000'
    environment:
      - STAGE=${STAGE}
      - DB_URL=${DB_URL}
      - TEST_DB_URL=${TEST_DB_URL}